package powerscale

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"testing"
)

// TestFixturesMatchDocumentedSchema fails if any testdata fixture contains a field that is
// not documented in the OneFS 9.14.0 response schema for its endpoint. onefs_schemas.json
// is generated by `make schemas` (tools/extract-schemas). This guard is what catches a
// fixture being hand-authored to match a parser instead of the real API.
func TestFixturesMatchDocumentedSchema(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("testdata", "onefs_schemas.json"))
	if err != nil {
		t.Fatalf("read onefs_schemas.json (run `make schemas`): %v", err)
	}
	var documented map[string][]string
	if err := json.Unmarshal(raw, &documented); err != nil {
		t.Fatalf("parse onefs_schemas.json: %v", err)
	}
	for fx, fields := range documented {
		doc := make(map[string]struct{}, len(fields))
		for _, f := range fields {
			doc[f] = struct{}{}
		}
		var obj any
		if err := json.Unmarshal(fixture(t, fx), &obj); err != nil {
			t.Fatalf("%s: %v", fx, err)
		}
		undocumented := undocumentedFields(obj, "", doc)
		sort.Strings(undocumented)
		if len(undocumented) > 0 {
			t.Errorf("fixture %s has fields not in OneFS 9.14.0 schema: %v", fx, undocumented)
		}
	}
}

// undocumentedFields walks v recursively and returns all dotted field paths
// that are absent from doc.
func undocumentedFields(v any, prefix string, doc map[string]struct{}) []string {
	var out []string
	switch node := v.(type) {
	case map[string]any:
		for k, sub := range node {
			p := k
			if prefix != "" {
				p = prefix + "." + k
			}
			if _, ok := doc[p]; !ok {
				out = append(out, p)
				continue // don't recurse into children of an undocumented parent
			}
			out = append(out, undocumentedFields(sub, p, doc)...)
		}
	case []any:
		for _, it := range node {
			out = append(out, undocumentedFields(it, prefix, doc)...)
		}
	}
	return out
}
